###Add student
POST http://localhost:8080/student/add
Content-Type: application/json

{
  "name": "Hojiakbar",
  "surname": "Nurmomatov",
  "age": 18,
  "gender": "MALE",
  "phone": "+998950923353",
  "balance": 0.0,
  "payment": false,
  "visible": true
}
### Student list
GET http://localhost:8080/student

### Student All show list
GET http://localhost:8080/student/showAll




